![Parked motorcycle](motorcycle.jpg)

You're working for a company that sells motorcycle parts, and they've asked for some help in analyzing their sales data!

They operate three warehouses in the area, selling both retail and wholesale. They offer a variety of parts and accept credit cards, cash, and bank transfer as payment methods. However, each payment type incurs a different fee.

The board of directors wants to gain a better understanding of wholesale revenue by product line, and how this varies month-to-month and across warehouses. You have been tasked with calculating net revenue for each product line and grouping results by month and warehouse. The results should be filtered so that only `"Wholesale"` orders are included.

They have provided you with access to their database, which contains the following table called `sales`:

## Sales
| Column | Data type | Description |
|--------|-----------|-------------|
| `order_number` | `VARCHAR` | Unique order number. |
| `date` | `DATE` | Date of the order, from June to August 2021. |
| `warehouse` | `VARCHAR` | The warehouse that the order was made from&mdash; `North`, `Central`, or `West`. |
| `client_type` | `VARCHAR` | Whether the order was `Retail` or `Wholesale`. |
| `product_line` | `VARCHAR` | Type of product ordered. |
| `quantity` | `INT` | Number of products ordered. | 
| `unit_price` | `FLOAT` | Price per product (dollars). |
| `total` | `FLOAT` | Total price of the order (dollars). |
| `payment` | `VARCHAR` | Payment method&mdash;`Credit card`, `Transfer`, or `Cash`. |
| `payment_fee` | `FLOAT` | Percentage of `total` charged as a result of the `payment` method. |


Your query output should be presented in the following format:

| `product_line` | `month` | `warehouse` |	`net_revenue` |
|----------------|-----------|----------------------------|--------------|
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_two | --- | --- | --- |
| ... | ... | ... | ... |

In [35]:
SELECT product_line,
       CASE
           WHEN date
                BETWEEN '2021-06-01' AND '2021-06-30' THEN
               'June'
           WHEN date
                BETWEEN '2021-07-01' AND '2021-07-31' THEN
               'July'
           WHEN date
                BETWEEN '2021-08-01' AND '2021-08-31' THEN
               'August'
       END AS month,
       ROUND(SUM(total) * (1 - payment_fee)::numeric, 2) AS net_revenue,
       warehouse
FROM sales
WHERE client_type = 'Wholesale'
GROUP BY product_line,
         warehouse,
         month,
         payment_fee
ORDER BY product_line ASC,
         month ASC,
         net_revenue DESC;

             product_line   month  net_revenue warehouse
0         Breaking system  August      3009.10   Central
1         Breaking system  August      2475.71      West
2         Breaking system  August      1753.19     North
3         Breaking system    July      3740.94   Central
4         Breaking system    July      3030.39      West
5         Breaking system    July      2568.55     North
6         Breaking system    June      3648.14   Central
7         Breaking system    June      1472.93     North
8         Breaking system    June      1200.64      West
9       Electrical system  August      4673.99     North
10      Electrical system  August      3095.22   Central
11      Electrical system  August      1229.45      West
12      Electrical system    July      5521.94   Central
13      Electrical system    July      1693.06     North
14      Electrical system    July       444.98      West
15      Electrical system    June      2875.93   Central
16      Electrical system    June      2002.30     North
17                 Engine  August      9433.48   Central
18                 Engine  August      2300.96     North
19                 Engine    July      1808.77   Central
20                 Engine    July       997.08     North
21                 Engine    June      6483.40   Central
22           Frame & body  August      8571.50   Central
23           Frame & body  August      7819.95     North
24           Frame & body  August       821.40      West
25           Frame & body    July      6093.11     North
26           Frame & body    July      3103.82   Central
27           Frame & body    June      5060.29   Central
28           Frame & body    June      4861.08     North
29           Frame & body    June      2751.96      West
30          Miscellaneous  August      1823.03     North
31          Miscellaneous  August      1722.40   Central
32          Miscellaneous  August       805.31      West
33          Miscellaneous    July      3087.31   Central
34          Miscellaneous    July      2380.63     North
35          Miscellaneous    July      1145.26      West
36          Miscellaneous    June      2258.20      West
37          Miscellaneous    June      1859.34   Central
38          Miscellaneous    June       508.86     North
39  Suspension & traction  August      5362.59   Central
40  Suspension & traction  August      4874.51     North
41  Suspension & traction  August      1069.99      West
42  Suspension & traction    July      6392.23   Central
43  Suspension & traction    July      3677.21     North
44  Suspension & traction    July      2909.98      West
45  Suspension & traction    June      7985.17     North
46  Suspension & traction    June      3291.80   Central
47  Suspension & traction    June      2348.83      West